import streamlit as st
from utils.graph_loader import load_graph, load_excerpts, load_metas
from utils.hf_llm import (
    conduct_graph_based_assessment, 
    process_assessment_answers, 
    generate_learning_roadmap,
    generate_enhanced_roadmap
)
from utils.retrieval import build_index, retrieve
from ui_components.graph_viz import draw_graph
from utils.scraper import scrape_resources
import os

st.set_page_config(layout="wide")
st.title("📚 Math Learning Navigator")
st.caption("🤖 AI-Powered Graph-Based Math Assessment & Learning Roadmaps")

# Initialize session state
if 'assessment_data' not in st.session_state:
    st.session_state.assessment_data = None
if 'problems_generated' not in st.session_state:
    st.session_state.problems_generated = False

# Load graph + build index once
@st.cache_data
def load_data():
    try:
        G = load_graph("/Users/jiawenyang/Documents/GitHub/-your_fingertips/math_firstyear.yaml")  # Use the first year math knowledge graph
        
        # Load excerpts and metas if they exist
        excerpts_dir = "data/excerpts"
        metas_path = "data/metas.json"
        
        texts = []
        metas = []
        
        if os.path.exists(excerpts_dir) and os.listdir(excerpts_dir):
            texts = load_excerpts(excerpts_dir)
        
        if os.path.exists(metas_path):
            try:
                metas = load_metas(metas_path)
            except:
                metas = []
        
        embed_model, idx = build_index(texts)
        return G, texts, metas, embed_model, idx
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return None, [], [], None, None

G, texts, metas, embed_model, idx = load_data()

if G is None:
    st.error("Failed to load math knowledge graph. Please check your data files.")
    st.stop()

# --- Learning Goal Input ---
st.header("🎯 What mathematical concept do you want to learn?")
goal = st.text_input(
    "Describe your learning goal", 
    placeholder="e.g., I want to understand calculus derivatives, learn about prime numbers, master linear algebra"
)

# Reset assessment if goal changes
if 'previous_goal' not in st.session_state:
    st.session_state.previous_goal = ""

if goal != st.session_state.previous_goal:
    st.session_state.assessment_data = None
    st.session_state.problems_generated = False
    st.session_state.previous_goal = goal

if goal and not st.session_state.problems_generated:
    if st.button("🔍 Find Target Topic & Generate Assessment"):
        with st.spinner("🤖 AI is analyzing your goal and finding related topics in the knowledge graph..."):
            # Use the new graph-based assessment workflow
            st.session_state.assessment_data = conduct_graph_based_assessment(goal, G)
            st.session_state.problems_generated = True
            st.rerun()

if st.session_state.problems_generated and st.session_state.assessment_data:
    assessment_data = st.session_state.assessment_data
    
    st.success("✅ Target topic identified and assessment problems generated!")
    
    # Show what the AI found
    st.subheader("🧠 AI Analysis Results:")
    col1, col2 = st.columns(2)
    with col1:
        st.write(f"**Target Topic:** {assessment_data['target_topic']}")
        st.write(f"**Current Level:** {assessment_data['intent'].get('current_level', 'Unknown')}")
    with col2:
        st.write(f"**Learning Context:** {assessment_data['intent'].get('learning_context', 'Unknown')}")
        st.write(f"**Related Topics Found:** {len(assessment_data['related_topics'])}")
    
    if assessment_data['related_topics']:
        with st.expander("📊 Related Topics from Knowledge Graph"):
            for topic in assessment_data['related_topics']:
                st.write(f"• {topic}")
    
    # Display math problems
    st.subheader("🧮 Mathematical Assessment Problems")
    st.caption("Solve these problems to help us understand your current knowledge level")
    st.info("💡 **Important:** These are actual math problems generated by AI. Show your work and reasoning!")
    
    problems = assessment_data['problems']
    answers = {}
    
    for i, problem_data in enumerate(problems):
        topic = problem_data['topic']
        problem_text = problem_data['problem']
        
        st.write(f"**Problem {i+1}: {topic}**")
        st.write(problem_text)
        answers[topic] = st.text_area(
            f"Your solution for {topic}:", 
            key=f"problem_{i}",
            height=120,
            placeholder="Show your work, explain your reasoning, and provide your answer..."
        )
        st.write("---")
    
    if st.button("📊 Submit Answers & Generate Learning Roadmap"):
        # Check if answers are provided
        unanswered = [topic for topic, answer in answers.items() if not answer.strip()]
        if unanswered:
            st.warning(f"Please provide answers for: {', '.join(unanswered)}")
        else:
            with st.spinner("🤖 AI is assessing your answers and determining your knowledge level..."):
                # Process answers and determine known/unknown topics
                assessment_results = process_assessment_answers(problems, answers)
                
                st.success("✅ Assessment completed!")
                
                # Show assessment results
                st.header("📊 Your Assessment Results")
                
                col1, col2 = st.columns(2)
                with col1:
                    st.subheader("✅ Topics You Know")
                    if assessment_results['known_topics']:
                        for topic in assessment_results['known_topics']:
                            result = assessment_results['assessment_results'][topic]
                            st.write(f"• **{topic}**: {result['assessment']}")
                            st.caption(f"   {result['explanation']}")
                    else:
                        st.write("No topics identified as fully understood")
                
                with col2:
                    st.subheader("📚 Topics to Learn")
                    if assessment_results['unknown_topics']:
                        for topic in assessment_results['unknown_topics']:
                            result = assessment_results['assessment_results'][topic]
                            st.write(f"• **{topic}**: {result['assessment']}")
                            st.caption(f"   {result['explanation']}")
                    else:
                        st.write("All assessed topics understood!")
                
                # Generate personalized learning roadmap using graph pathfinding + LLM
                with st.spinner("🗺️ AI is creating your personalized learning roadmap using graph pathfinding..."):
                    roadmap_result = generate_enhanced_roadmap(
                        G,  # Pass the graph for pathfinding
                        assessment_data['intent'],
                        assessment_results['assessment_results'],
                        assessment_results['known_topics'],
                        assessment_results['unknown_topics']
                    )
                    
                    # Extract roadmap and metadata
                    roadmap = roadmap_result.get('roadmap', roadmap_result) if isinstance(roadmap_result, dict) else roadmap_result
                    roadmap_metadata = roadmap_result.get('metadata', {}) if isinstance(roadmap_result, dict) else {}
                
                # Display the learning roadmap
                st.header("🗺️ Your Personalized Learning Roadmap")
                st.subheader(f"From your current knowledge to: {assessment_data['target_topic']}")
                
                # Show pathfinding metadata if available
                if roadmap_metadata:
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric("📊 Total Steps", roadmap_metadata.get('total_steps', 'N/A'))
                    with col2:
                        st.metric("🎯 Starting From", roadmap_metadata.get('starting_from', 'N/A'))
                    with col3:
                        st.metric("🔄 Alternative Paths", roadmap_metadata.get('alternative_paths', 'N/A'))
                    
                    if roadmap_metadata.get('path_summary'):
                        st.info(f"🛤️ **Optimal Learning Path**: {roadmap_metadata['path_summary']}")
                
                st.caption("🤖 This roadmap uses graph pathfinding to find the shortest learning path combined with AI-generated activities")
                
                if roadmap:
                    for step, activities in roadmap.items():
                        with st.expander(f"**{step}**", expanded=True):
                            for activity in activities:
                                st.write(f"• {activity}")
                            
                            # Add progress tracker
                            if st.checkbox(f"Mark {step} as completed", key=f"step_{step}"):
                                st.success(f"✅ {step} completed!")
                else:
                    st.warning("Could not generate roadmap. Please try with a different learning goal.")
                
                # Show pathfinding details
                if isinstance(roadmap_result, dict) and 'pathfinding_info' in roadmap_result:
                    pathfinding_info = roadmap_result['pathfinding_info']
                    if 'all_paths' in pathfinding_info:
                        with st.expander("🗺️ All Possible Learning Paths", expanded=False):
                            st.caption("Alternative routes from your known topics to the target")
                            for path_info in pathfinding_info['all_paths']:
                                if path_info['length'] is not None:
                                    st.write(f"**{path_info['start']}** → **{path_info['target']}** ({path_info['length']} steps)")
                                    st.code(path_info['path'])
                                else:
                                    st.write(f"**{path_info['start']}** → **{path_info['target']}**: No path available")
                
                # Show detailed assessment breakdown
                with st.expander("🔍 Detailed Assessment Breakdown", expanded=False):
                    st.caption("See how the AI assessed each of your responses")
                    
                    # Add option to show correct solutions
                    show_solutions = st.checkbox("🔓 Show correct solutions (for learning)", key="show_solutions")
                    
                    for i, problem_data in enumerate(problems):
                        topic = problem_data['topic']
                        problem_text = problem_data['problem']
                        user_answer = answers[topic]
                        result = assessment_results['assessment_results'][topic]
                        
                        st.write(f"**Problem {i+1}: {topic}**")
                        st.write(f"*Problem:* {problem_text}")
                        st.write(f"*Your Answer:* {user_answer}")
                        st.write(f"*AI Assessment:* {result['assessment']}")
                        st.write(f"*Explanation:* {result['explanation']}")
                        
                        # Show correct solution if requested and available
                        if show_solutions and 'correct_solution' in result:
                            with st.expander(f"📖 Correct Solution for {topic}", expanded=False):
                                st.write(result['correct_solution'])
                                st.caption("Use this to understand the correct approach and learn from any mistakes.")
                        
                        st.write("---")
                
                # Get learning resources
                st.header("📚 Personalized Learning Resources")
                st.caption("AI-generated resources tailored to your specific assessment results")
                
                # Generate personalized resources based on assessment
                from utils.scraper import generate_personalized_resources
                
                personalized_resources = generate_personalized_resources(
                    target_topic=assessment_data['target_topic'],
                    assessment_results=assessment_results['assessment_results'],
                    known_topics=assessment_results['known_topics'],
                    unknown_topics=assessment_results['unknown_topics'],
                    level=assessment_data['intent'].get('current_level', 'beginner')
                )
                
                # Display personalized resources
                for i, resource in enumerate(personalized_resources, 1):
                    with st.expander(f"📖 Resource {i}: {resource['title']}", expanded=False):
                        st.write(f"**Type:** {resource['type']}")
                        st.write(f"**Description:** {resource['description']}")
                        st.write(f"**Time Needed:** {resource['time']}")
                        if resource.get('personalized', False):
                            st.success("🎯 Personalized for your specific needs")
                        
                        # Add a "completed" checkbox for tracking
                        if st.checkbox(f"Mark as completed", key=f"resource_{i}"):
                            st.success("✅ Resource completed!")
                
                # Add step-specific resources for each roadmap step
                st.subheader("🎯 Step-by-Step Learning Resources")
                st.caption("Specific resources for each step in your learning roadmap")
                
                from utils.scraper import generate_step_specific_resources
                
                for step_name, step_details in roadmap.items():
                    if len(step_details) >= 3:  # Has topic, activity, skill format
                        # Extract topic, activity, skill from formatted strings
                        topic_line = step_details[0].replace("📚 **Topic**: ", "")
                        activity_line = step_details[1].replace("🎯 **Activity**: ", "")
                        skill_line = step_details[2].replace("💡 **Skill**: ", "")
                        
                        with st.expander(f"📚 {step_name} Resources", expanded=False):
                            st.write(f"**Focus:** {topic_line}")
                            st.write(f"**Activity:** {activity_line}")
                            st.write(f"**Skill Goal:** {skill_line}")
                            
                            # Generate step-specific resources
                            step_resources = generate_step_specific_resources(
                                step_topic=topic_line,
                                step_activity=activity_line,
                                step_skill=skill_line,
                                level=assessment_data['intent'].get('current_level', 'beginner')
                            )
                            
                            st.write("**Recommended Resources:**")
                            for j, step_resource in enumerate(step_resources, 1):
                                st.write(f"{j}. **{step_resource['type']}**: {step_resource['title']}")
                                if step_resource.get('supports_activity'):
                                    st.write(f"   - *Supports Activity*: {step_resource['supports_activity']}")
                                if step_resource.get('develops_skill'):
                                    st.write(f"   - *Develops Skill*: {step_resource['develops_skill']}")
                                st.write(f"   - *Time*: {step_resource['time']}")
                                st.write("")

    # Add a reset button
    if st.button("🔄 Start New Assessment"):
        st.session_state.assessment_data = None
        st.session_state.problems_generated = False
        st.session_state.previous_goal = ""
        st.rerun()

# --- Math Knowledge Graph ---
st.header("🗺️ Comprehensive Math Knowledge Graph")
st.write("Explore the relationships between mathematical concepts:")
st.caption(f"📊 **Graph Statistics:** {G.number_of_nodes()} concepts, {G.number_of_edges()} relationships")

# Highlight target topic if found
if st.session_state.assessment_data and st.session_state.assessment_data['target_topic']:
    st.info(f"🎯 **Your Target Topic:** {st.session_state.assessment_data['target_topic']}")
    if st.session_state.assessment_data['related_topics']:
        st.info(f"🔗 **Related Topics:** {', '.join(st.session_state.assessment_data['related_topics'][:3])}...")

try:
    graph_html = draw_graph(G)
    st.components.v1.html(graph_html, height=600)
except Exception as e:
    st.error(f"Error displaying graph: {e}")
    st.write("Graph visualization temporarily unavailable.")

# --- Sidebar info ---
st.sidebar.header("ℹ️ About Math Navigator")
st.sidebar.write("This tool uses **AI-powered graph-based assessment** to create personalized math learning roadmaps.")
st.sidebar.markdown("**🤖 AI Features:**")
st.sidebar.write("• Graph-based topic identification")
st.sidebar.write("• Real-time math problem generation")
st.sidebar.write("• Intelligent answer assessment")
st.sidebar.write("• Personalized learning roadmaps")
st.sidebar.markdown("**📊 Knowledge Graph:**")
st.sidebar.write(f"• {G.number_of_nodes()} mathematical concepts")
st.sidebar.write(f"• {G.number_of_edges()} concept relationships")
st.sidebar.write("• First-year mathematics topics")
st.sidebar.write("• Prerequisite relationships")
st.sidebar.markdown("**How it works:**")
st.sidebar.write("1. 🎯 AI finds your target topic in the graph")
st.sidebar.write("2. 🔗 Identifies related prerequisite topics") 
st.sidebar.write("3. 🧮 Generates actual math problems")
st.sidebar.write("4. 📊 AI assesses your solutions")
st.sidebar.write("5. 🗺️ Creates roadmap from known to unknown")

# Add model info in sidebar
st.sidebar.markdown("---")
st.sidebar.markdown("**🔧 Technical Details:**")
st.sidebar.write("• Model: Qwen2.5-0.5B-Instruct")
st.sidebar.write("• Graph-based problem generation")
st.sidebar.write("• Real-time answer assessment")
st.sidebar.write("• Knowledge-gap identification")

# Add study tips
st.sidebar.markdown("---")
st.sidebar.markdown("**💡 Study Tips:**")
st.sidebar.write("🧮 Show your work clearly")
st.sidebar.write("📝 Explain your reasoning")
st.sidebar.write("❓ Don't be afraid to say 'I don't know'")
st.sidebar.write("🔄 Practice problems regularly")
st.sidebar.write("📈 Build from what you know")